[ci skip] Apply placemat v2
cybozu-go/neco pull request #1418
Opened 2021-02-18 06:07 UTC by ysksuzuki

Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>

2021-03-08 01:11 UTC, ymmt2005 requested changes

2021-03-08 01:11 UTC, ymmt2005 commented on dctest/test.sh
> +if [ "$PLACEMAT_MAJOR_VERSION" = "1" ]; then
I guess this block can be removed because we are replacing
placemat v1 with v2 in the same PR.  Am I correct?

2021-03-08 01:36 UTC, ysksuzuki commented on dctest/test.sh
> +if [ "$PLACEMAT_MAJOR_VERSION" = "1" ]; then
This is needed for the upgrade test suit. That bootstraps neco using release branch which depends on placemat v1 and run the upgrade test suit using placemat v2 feature branch. We can remove this block after this PR is released.

2021-03-08 01:39 UTC, ysksuzuki commented on dctest/Makefile
> +	@echo 'Placemat is running.  To kill it, do "make stop".'
> Is make stop correct? I'm asking because there is stop-placemat-inside-container.

`stop-placemat-inside-container` is correct. Will fix it.

2021-03-08 01:39 UTC, ymmt2005 commented on dctest/test.sh
> +if [ "$PLACEMAT_MAJOR_VERSION" = "1" ]; then
I see.

2021-03-08 01:47 UTC, ysksuzuki commented on dctest/Makefile
> +	@echo 'Placemat is running.  To kill it, do "make stop".'
> Can we replace make placemat? If we can, it would be simpler.

I agree with you, but `gcloud compute ssh --command='/home/cybozu/run.sh'` waits until placemat process ends when I replace `make placemat` with it. I think we can replace with it after we move to Self Hosted Runner.

2021-03-08 02:08 UTC, ysksuzuki commented on Makefile
> +	go generate ./menu/menuassets/generate_rule.go
`statik.go` is required to run placemat-menu test, so I added `go generate` here. I couldn't come up with a better idea.

2021-03-08 03:36 UTC, ymmt2005 commented on Makefile
> +	go generate ./menu/menuassets/generate_rule.go
I'd suggest generating `statik.go` beforehand and adding it to git.

2021-03-09 01:27 UTC, ymmt2005 approved these changes
LGTM

2021-03-10 05:42 UTC, merged