Change sabakan GQL client
cybozu-go/neco pull request #1498
Opened 2021-03-29 04:39 UTC by masa213f

Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

2021-04-02 09:34 UTC, binoue approved these changes
LGTM

2021-04-02 15:33 UTC, morimoto-cybozu requested changes

2021-04-02 15:33 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller.go
> +				"machine-type": undefinedType,
A hyphen cannot be used for field names.
https://github.com/cybozu-go/log/blob/v1.6.0/formatter.go#L42

2021-04-02 15:33 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller.go
> +		if !ok || m.State == newState {
The check of `m.State == newState` is new in this PR.
It seems reasonable, but I'm afraid there is some reason not to do this check in the old code...

By the way, `newState == m.State` would be preferable.

2021-04-02 15:33 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller.go
> +			c.ClearUnhealthy(m)
This is not called if a machine transits from Unhealthy to Retiring because a retiring machine is not included in the newStateMap.
It leaves an entry in `c.unhealthyMachines`, while it affects just a little.

2021-04-02 15:33 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller.go
> +		log.Info("do health check", map[string]interface{}{
Do we need this log?

2021-04-02 15:33 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller.go
>  		newState, hasTransition := mss.decideMachineStateCandidate()
`hasTransition` seems misleading.

2021-04-02 15:33 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller_test.go
> +	machineTypeSkip := &machineType{
`machineTypeNoMetricsCheck` or `machineTypeSerfOnly` would be more meaningful.

2021-04-02 15:33 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller_test.go
> +			message: "healthcheck: transition machine state to unhealthy due to warning disks become larger than one",
The test messages need refining.

2021-04-05 02:37 UTC, masa213f commented on pkg/sabakan-state-setter/controller.go
> +		if !ok || m.State == newState {
I am one of the members who wrote the initial sabakan-state-setter.
As far as I remember, there is not any reason in the old code...

2021-04-05 04:23 UTC, masa213f commented on pkg/sabakan-state-setter/controller.go
> +		if !ok || m.State == newState {
Without the `!ok` check, the state of the StateUpdating, StateRetiring, or StateRetired machines will be updated unnecessarily.
So this condition needs `!ok`.

2021-04-05 04:26 UTC, masa213f commented on pkg/sabakan-state-setter/controller_test.go
> +			message: "healthcheck: transition machine state to unhealthy due to warning disks become larger than one",
Update the tests. de6a72b
The test needs to do the health checks of multiple machines. So I have updated this test with the message.

2021-04-05 04:30 UTC, masa213f commented on pkg/sabakan-state-setter/controller.go
> +			c.ClearUnhealthy(m)
I changed the location of `ClearUnhealthy`.
In most cases, this leak will be prevented by this fix.
9468abd

2021-04-05 05:59 UTC, morimoto-cybozu requested changes

2021-04-05 05:59 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller.go
> +		if !ok || m.State == newState {
Checking `!ok` is OK:-)
I have a feeling of strangeness in the order of the equality check, though it might be a matter of taste.

```suggestion
		if !ok || newState == m.State {
```

2021-04-05 05:59 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller.go
> +		}
It would be good to call `c.ClearUnhealthy(m)` in an `else` clause.
Even without that call, `c.unhealthyMachines[m.Serial]` will be cleared in the next invocation of `runOnce()` because `newState == m.State` will become true in most cases.
But I don't think it is intuitive.

Using `switch` might help.

```
switch {
case !ok || newState == m.State:
    c.CleanUnhealthy(m)
    continue
case newState == sabakan.Stateunhealthy:
    if ok := c.RegisterUnhealthy(m, now); !ok {
        continue
    }
default:
    c.CleanUnhealthy(m)
}
```

2021-04-05 05:59 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller.go
> +		return map[string]sabakan.MachineState{}
The returned map will not be modified, so we don't need to make an empty map here.

```suggestion
		return nil
```

2021-04-05 06:15 UTC, morimoto-cybozu commented on pkg/sabakan-state-setter/controller_test.go
> +				"00000003": sabakan.StateUnreachable, // serf status is failed
```suggestion
				"00000000": sabakan.StateUnhealthy,   // one of two CPUs is issuing a warning
				"00000001": sabakan.StateUnhealthy,   // all HDD are unhealthy; # of healthy HDDs falls below MinimumHealthyCount (0 < 1)
				"00000002": sabakan.StateHealthy,     // one of two HDDs is unhealthy, but it is acceptable
				"00000003": sabakan.StateUnreachable, // serf status is "failed"
```

2021-04-05 08:38 UTC, masa213f commented
@morimoto-cybozu 
I reflected comments and check the behavior on the dctest.
Please review again.

2021-04-05 09:08 UTC, morimoto-cybozu approved these changes
LGTM

2021-04-05 09:08 UTC, merged