Add force option to 'neco tpm clear'
cybozu-go/neco pull request #1533
Opened 2021-04-15 02:18 UTC by masa213f

- For safety, add `--force` option to `neco tpm clear`.
- Output failure messages of `neco tpm clear` in the sabakan-state-setter log.

Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

2021-04-15 08:57 UTC, ymmt2005 requested changes
LGTM

2021-04-15 08:57 UTC, ymmt2005 commented on pkg/sabakan-state-setter/necocommand.go
> +	return outBuf.String(), errBuf.String(), err
Why don't you use `CombinedOutput()`?

2021-04-16 00:29 UTC, masa213f commented on pkg/sabakan-state-setter/necocommand.go
> +	return outBuf.String(), errBuf.String(), err
That's good. I fixed it.

2021-04-16 00:32 UTC, ymmt2005 approved these changes
LGTM

2021-04-16 02:21 UTC, merged