Force power on/off
cybozu-go/neco pull request #1807
Opened 2021-11-01 02:39 UTC by masa213f

Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

2021-11-01 07:25 UTC, morimoto-cybozu requested changes

2021-11-01 07:25 UTC, morimoto-cybozu commented on pkg/neco/cmd/tpm_clear.go
> +				panic(fmt.Sprintf("unknown logic type: %d", logicType))
I'm not sure why returning an error is inappropriate.

2021-11-01 07:25 UTC, morimoto-cybozu commented on pkg/neco/cmd/tpm_clear.go
> +				return power(ctx, "stop", machine.Spec.BMC.IPv4)
To power-off anyway would be good.

I prefer to return an error here even when power-off succeeds, because the operator expects "neco tpm clear" both to clear the TPM devices and to power-off the machines.
In this case the TPM devices are not cleared, so not all expectations are fulfilled.
This situation should be expressed by an error rather than a warning.

For QEMU and TPM 1.2 machines, the operator should not expect the command to clear the TPM devices, so returning non-error would be appropriate.

2021-11-02 02:03 UTC, masa213f commented on pkg/neco/cmd/tpm_clear.go
> +				panic(fmt.Sprintf("unknown logic type: %d", logicType))
That's right. Functionally both returning an error and calling `panic()` are almost the same.

But this switch statement only accepts the following constants. And this `default` case is not reached.
So I thought it would be suitable to use `panic()`.

```
const (
	tpmClearLogicTypePowerOff = iota // If clearing TPM is not supported, shutdown the machine.
	tpmClearLogicTypeDellRedfish
)
```

2021-11-02 02:31 UTC, masa213f commented on pkg/neco/cmd/tpm_clear.go
> +				return power(ctx, "stop", machine.Spec.BMC.IPv4)
That's good. https://github.com/cybozu-go/neco/pull/1807/commits/212012ef740c764f494fd96cafd0853fd60402b3
When logicType for a target machine is not defined, `neco tpm clear` will output the following logs.

```
2021-11-02T02:19:03.222572Z ubuntu-local neco warning: "unknown machine type; shutdown" machine_type="MACHINE_TYPE" node="NNN.NNN.NNN.NNN" result=null serial="SERIAL"
2021-11-02T02:19:03.222647Z ubuntu-local neco error: "unknown machine type"
```

2021-11-02 02:41 UTC, morimoto-cybozu approved these changes
LGTM

2021-11-02 06:31 UTC, merged