fix permission of yq binary
cybozu-go/neco pull request #2006
Opened 2022-05-19 05:34 UTC by umezawatakeshi

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

2022-05-19 09:51 UTC, morimoto-cybozu requested changes

2022-05-19 09:51 UTC, morimoto-cybozu commented on Makefile.tools
> +	test `find $(SBINDIR) -type f -a \( ! -perm -111 \) | wc -l` = 0
`$$(...)` would be better for appearance.

```suggestion
	test -z "$$(find $(BINDIR) $(SBINDIR) -type f -a \( \! -perm -111 \) | tee /dev/stderr)"
```

2022-05-20 07:31 UTC, morimoto-cybozu approved these changes
LGTM
`artifacts.go` requires update.  Please rebase after the branch promtail-v2.5.0 is merged.

2022-05-23 08:04 UTC, morimoto-cybozu requested changes

2022-05-23 08:04 UTC, morimoto-cybozu commented on Makefile.tools
> +	test -z $$(find $(BINDIR) $(SBINDIR) -type f -a \( ! -perm -111 \) | tee /dev/stderr)
The operator for `test -z` should be one string.
Try `test -z $(ls -a); echo $?` and `test -z "$(ls -a)"; echo $?` for example.
Though the results are both evaluated to False, the former one produces an error.

It is recommended to escape `!`.

```suggestion
	test -z "$$(find $(BINDIR) $(SBINDIR) -type f -a \( \! -perm -111 \) | tee /dev/stderr)"
```

2022-05-23 08:42 UTC, umezawatakeshi commented on Makefile.tools
> +	test -z $$(find $(BINDIR) $(SBINDIR) -type f -a \( ! -perm -111 \) | tee /dev/stderr)
There is no excuse for what I have (not) done...

2022-05-23 09:38 UTC, merged