Added the ability to switch the site.yml used for each environment
cybozu-go/neco pull request #2044
Opened 2022-08-01 07:56 UTC by zeroalphat

Since kubernetes configuration needs to be changed for each environment, we have added the ability to change the file to be loaded for each environment.
As an example, if the datacenter value is dc1, site-gcp.yml will be loaded.

2022-08-02 05:27 UTC, zoetrope commented on ignitions/common/common-gcp.yml
> +files:
I think this file is redundant.
Couldn't you write the following?

```
include: common.yml
files:
  - /etc/k8s-containerd/conf.d/registry-local.registry.gcp0.dev-ne.co/hosts.toml
```

2022-08-02 06:19 UTC, zoetrope commented on progs/sabakan/upload.go
> +		datacenter = mcs[0].Spec.Labels["datacenter"]
If you want the cluster name, you can read it from `/etc/neco/cluster`.

2022-08-02 06:24 UTC, zoetrope commented on progs/sabakan/upload.go
> +			path = filepath.Join(neco.IgnitionDirectory, "roles", role, "site-stage0.yml")
This code is ad hoc.
It does not support other data centers.

Couldn't you write the following?

```
path = filepath.Join(neco.IgnitionDirectory, "roles", role, fmt.Sprintf("site-%s.yml", clusterName))
```

2022-08-02 06:29 UTC, zoetrope commented on progs/sabakan/upload.go
> +func verificationOfFileExistence(path string) bool {
I think this func name is a little long.
For example, `fileExists` is concise.

2022-08-02 06:33 UTC, zoetrope commented on ignitions/common/common.yml
>    - /etc/k8s-containerd/conf.d/localhost:5050/hosts.toml
I noticed that this file should be deployed only on stage0 and gcp.

2022-08-02 06:35 UTC, zoetrope commented on ignitions/common/files/etc/k8s-containerd/conf.d/registry-local.registry.svc:5000/hosts.toml
> +server = "http://registry-local.registry.svc:5000"
Is this file necessary?

2022-08-02 06:37 UTC, zoetrope commented on ignitions/common/systemd/k8s-containerd.service
> +Environment="NO_PROXY=registry.svc,ceph-object-store.svc"
Is `ceph-object-store.svc` necessary when redirect is disabled?

2022-08-02 06:51 UTC, zeroalphat commented on ignitions/common/common-gcp.yml
> +files:
Fixed redundant configuration file at 552cc0d31e270caefa54d7a049bd862c4e23b933

2022-08-02 06:54 UTC, zeroalphat commented on progs/sabakan/upload.go
> +		datacenter = mcs[0].Spec.Labels["datacenter"]
Retrieve information in `/etc/neco/cluster` instead of retrieving datacenter label at 4d72f5b1dceab8bd6ea5d08129ffe6256695653c

2022-08-02 06:55 UTC, zeroalphat commented on progs/sabakan/upload.go
> +			path = filepath.Join(neco.IgnitionDirectory, "roles", role, "site-stage0.yml")
Fixed at 126f14579e5da45dfb665056ff666999c105ad31

2022-08-02 07:59 UTC, zeroalphat commented on ignitions/common/files/etc/k8s-containerd/conf.d/registry-local.registry.svc:5000/hosts.toml
> +server = "http://registry-local.registry.svc:5000"
The file was not needed, so I deleted it at b5308a3422fe2fac7efd0386a9e693eb697af723

2022-08-02 08:00 UTC, zeroalphat commented on progs/sabakan/upload.go
> +func verificationOfFileExistence(path string) bool {
Renamed funciton at 538eba2585626fc2d28fe2d221b08014e435ed5a

2022-08-02 08:18 UTC, zeroalphat commented on ignitions/common/systemd/k8s-containerd.service
> +Environment="NO_PROXY=registry.svc,ceph-object-store.svc"
`ceph-object-store.svc` was not needed, so I deleted it and reverted the changes.
aa1053b427d65163edb0e633a2a46a6e2bfdf960

2022-08-02 09:09 UTC, zeroalphat commented on ignitions/common/common.yml
>    - /etc/k8s-containerd/conf.d/localhost:5050/hosts.toml
Removed settings from common.yml at 0b9c070ca48bf1a1ca1c966ec71a0766151938c0

2022-08-03 05:46 UTC, morimoto-cybozu requested changes

2022-08-03 05:46 UTC, morimoto-cybozu commented on ignitions_test.go
> +		if s, _ := regexp.MatchString("site(-[a-z]+[0-9]*|).yml", info.Name()); s {
We have very few restrictions on the environment names.
`site(-.*|)\.yml` or `site.*\.yml` would be appropriate.

2022-08-03 08:18 UTC, zeroalphat commented on ignitions/common/files/etc/k8s-containerd/conf.d/registry-local.registry.stage0.cybozu-ne.co/hosts.toml
> +server = "https://registry-local.registry.cyozu-ne.co"
Added environment name at 59662d6ba87b72fa4b860088e9f264451b69f127

2022-08-03 08:20 UTC, zeroalphat commented on ignitions/roles/ss/site-gcp0.yml
> +  - /etc/udev/rules.d/99-neco.rules
I forgot to add `ignitions/roles/ss/site-stage0.yml`.
I added it at d3eac2dc2e91ca0d24f1f9b17c3e1d0a597cad23.

2022-08-03 08:25 UTC, zeroalphat commented on docs/files.md
> +If `site-<environment>.yml` does not exist, `site.yml` is used.
I have changed from `<enviroment>` to using `<cluster>` at 1059de772901a44a299788fabda59293bf70513a

2022-08-03 08:25 UTC, zeroalphat commented on docs/ignition.md
> +    To place different files for each environment, create a new `common-<environment>.yml` and specify it in `site-<environment>.yml`.
I have changed from `<enviroment>` to using `<cluster>` at 1059de772901a44a299788fabda59293bf70513a

2022-08-03 08:29 UTC, zeroalphat commented on docs/files.md
> +The directory must contain an entry point file `site.yml|site-<environment>.yml`, which defined in [sabakan ignition spec.][ignition.md].
I have corrected it at 03361eb4e0bcfb16b57345add9ccfd0a2592afb5.

2022-08-03 08:31 UTC, zeroalphat commented on progs/sabakan/upload.go
> +	return err == nil
I have changed it so that an error is returned to `uploadIgnitions()` if there is an error except that the file does not exist.
bf504c69ca711968f04838ed7b2d547bd0a654c0

2022-08-05 08:01 UTC, zeroalphat commented on ignitions_test.go
> +			}
Changed to compare the list of files in all `site.yml | site-<env>.yaml` with the list of files in the directory.
3fe55abc9752bb5c3373c1ad3f07e1b2e2214131
2618eaa54f6a068243b05a1aebae988af275293e
29b6164ed7c28f2f1e95d16be82873f17be560a0

2022-08-08 08:45 UTC, zeroalphat commented on ignitions/roles/cs/site-gcp0.yml
> +    enabled: true
Added feature to generate a config file for each environment using jsonnet.

2618b40ba93466e30fdb6b42e976fd955fb8fa35

2022-08-10 10:48 UTC, morimoto-cybozu requested changes

2022-08-10 10:48 UTC, morimoto-cybozu commented on envGenerate/template/Makefile
> +		cat $(TEMP_DIR)/$*.json |jq 'del(.[][] | select(length == 0))' | $(YQ) --no-doc ".[\"$$i\"] | .[0] headComment=\"$(AUTOGEN_COMMENT)\" | .[] | splitDoc" - --prettyPrint > $(ROOT_DIR)/$$i; \
`--no-doc` seems to cancel `| splitDoc`.

```suggestion
		cat $(TEMP_DIR)/$*.json |jq 'del(.[][] | select(length == 0))' | $(YQ) ".[\"$$i\"] | .[0] headComment=\"$(AUTOGEN_COMMENT)\" | .[]" - --prettyPrint > $(ROOT_DIR)/$$i; \
```

2022-08-10 10:48 UTC, morimoto-cybozu commented on envGenerate/template/Makefile
> +	$(SUDO) apt-get update && $(SUDO) apt-get -y install wget; \
```suggestion
	$(SUDO) apt-get update && $(SUDO) apt-get -y install wget
```

2022-08-10 10:48 UTC, morimoto-cybozu commented on docs/files.md
> +If `site-<cluster>.yml` does not exist, `site.yml` is used.
We need a description how the value of `<cluster>` is determined.

2022-08-10 10:48 UTC, morimoto-cybozu commented on envGenerate/template/utility.libsonnet
> +    std.filter(function(x) std.count(settings.migrating_teams, x) > 0, self.get_teams(settings)),
Not used, as well as `get_tenants`, `get_destination_apps`, and `get_app`.

2022-08-10 10:48 UTC, morimoto-cybozu commented on ignitions_test.go
> +			filestateInDir = map[string]bool{}
My intuition tells me that this code could be more structured.
It seems unnatural to:
* use two counters and compare them to determine the end of some processing
* initialize `filestateInDir` manually
* pass `final` to a helper function

How about using `siteYAMLsByRole := make(map[string][]string)` instead of `roleCount`?
You can hold a list of YAML file names for each role.
And you can introduce a nested loop.
```
for role, siteYAMLs := range siteYAMLsByRole {
  filestateInDir := make(map[string]bool)
  for _, sy := range siteYAMLs {
    testIgnitionTemplates(...)
  }
  checkForFlag(...)  // This can be placed outside of testIgnitionTemplates.
}
```

2022-08-12 02:00 UTC, zeroalphat commented on ignitions_test.go
> +			filestateInDir = map[string]bool{}
Fix unnatural elements of the code at 9eeaac02074021a66965f0d2a49d7e652d5c30d6.

2022-08-12 02:00 UTC, zeroalphat commented on envGenerate/template/Makefile
> +	# Thus, jq "with_entries(.values |= sort)" sorts all the arrays of an object members.
Remove stale comments at c461fdcce546508d18ff854e258a588423595914.

2022-08-12 02:01 UTC, zeroalphat commented on envGenerate/template/Makefile
> +	$(SUDO) apt-get update && $(SUDO) apt-get -y install wget; \
Delete unneeded material at 9e1a72b76893734b20c87f6083141426eeb3bcaf.

2022-08-12 02:02 UTC, zeroalphat commented on docs/files.md
> +If `site-<cluster>.yml` does not exist, `site.yml` is used.
Add a description of the cluster at 39427efac7bb02c0450036973be42edf0c3be023.

2022-08-12 02:02 UTC, zeroalphat commented on envGenerate/template/utility.libsonnet
> +    std.filter(function(x) std.count(settings.migrating_teams, x) > 0, self.get_teams(settings)),
Remove unused functions at ae88623240dec97b1a56b678bbd8733a5cf4c5c8.

2022-08-12 02:05 UTC, zeroalphat commented on envGenerate/template/Makefile
> +		cat $(TEMP_DIR)/$*.json |jq 'del(.[][] | select(length == 0))' | $(YQ) --no-doc ".[\"$$i\"] | .[0] headComment=\"$(AUTOGEN_COMMENT)\" | .[] | splitDoc" - --prettyPrint > $(ROOT_DIR)/$$i; \
Removed `--no-doc`, `| splitDoc` and configured the array not to split into multiple documents.
 08840932a8458590a06d7695a5c2bceb0e5a338d.

2022-08-12 09:16 UTC, morimoto-cybozu requested changes

2022-08-12 09:16 UTC, morimoto-cybozu commented on envGenerate/template/utility.libsonnet
> +    std.filter(function(x) std.count(settings.migrating_teams, x) > 0, self.get_teams(settings)),
`get_migrating_teams` can also be removed.

I have no other comments.
Once zoetrope-san also approves these commits, could you please squash minute commits?
If you can't be confident about rebasing, please let me know; let's run `git rebase` together on Zoom!

2022-08-15 01:22 UTC, zeroalphat commented on envGenerate/template/utility.libsonnet
> +    std.filter(function(x) std.count(settings.migrating_teams, x) > 0, self.get_teams(settings)),
Deleted functions at 9b3f34c9fbd3a4a3497cd1c49aa28322b0217641.
Thank you for your review.
I will rebase when I get an approve from zoetrope san.

2022-08-15 02:58 UTC, morimoto-cybozu submitted a review, later dismissed
LGTM

2022-08-16 08:00 UTC, zoetrope approved these changes

2022-08-16 08:33 UTC, morimoto-cybozu approved these changes
LGTM

2022-08-16 09:17 UTC, merged