Add document explaining ignition-template
cybozu-go/neco pull request #2102
Opened 2022-09-26 06:32 UTC by zeroalphat

Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>

2022-09-28 11:04 UTC, morimoto-cybozu requested changes

2022-09-28 11:04 UTC, morimoto-cybozu commented on docs/ignition-template.md
> +[ignition-template](../ignition-template) automatically generates configuration files for each environment such as `common-<cluster>.yml` and `site-<cluster>.yml`.
It would be good to place some introduction about [Ignition template system](https://github.com/cybozu-go/sabakan/blob/master/docs/ignition_template.md).
You can just point to `docs/ignition.md`.

This document should be pointed from `docs/ignition.md`.

2022-09-28 11:04 UTC, morimoto-cybozu commented on docs/ignition-template.md
> +Configgenerator command cluster are optional and will work even if only role is specified in the configgenerator command.
```suggestion
Configgenerator command takes a cluster as an option and will work even if only the role is specified.
```

2022-09-30 00:35 UTC, zeroalphat commented on docs/ignition-template.md
> +Configgenerator command cluster are optional and will work even if only role is specified in the configgenerator command.
Fix in 1a4505f90eeaf3c500a05938b796de6770092b99

2022-09-30 00:40 UTC, zeroalphat commented on docs/ignition-template.md
> +[ignition-template](../ignition-template) automatically generates configuration files for each environment such as `common-<cluster>.yml` and `site-<cluster>.yml`.
The proper use of the terms was not being used, so the config file are replaced with two terms: ignition template and pseudo-ignition.
b92b78602c1aa7bb6494cfcb4722d07551c5a69e

Also add reference to documentation.
a0915aa6478e333823b97650ba3f740504535691

2022-09-30 03:14 UTC, morimoto-cybozu requested changes

2022-09-30 03:14 UTC, morimoto-cybozu commented on docs/ignition.md
> +    For information on how to generate the file, please refer to the [ignition-template](./ignition-template) documentation.
I once suggested that this document should point `ignition-template.md`.
But I found that this document is focused on the entire boot sequence of Flatcar, not on the Ignition template system.
So I would revise my suggestion; `ignition-template.md` should be pointed from `files.md`.

```
If `site-<cluster>.yml` does not exist, `site.yml` is used.

The entry point files are generated according to [`settings.json`](../ignition-template/settings.json).
For information on how to generate the files, please refer to the [ignition-template](./ignition-template.md) documentation.
```

2022-09-30 05:10 UTC, zeroalphat commented on docs/ignition.md
> +    For information on how to generate the file, please refer to the [ignition-template](./ignition-template) documentation.
Made a change to reference igniti-template.md from files.md.
a46be214001c03f7f7c1dc47ef5554d127d47e69

2022-09-30 05:28 UTC, morimoto-cybozu submitted a review, later dismissed
LGTM

2022-09-30 06:23 UTC, morimoto-cybozu approved these changes

2022-09-30 07:30 UTC, merged