Change output destination to stdin
cybozu-go/neco pull request #2116
Opened 2022-10-13 04:34 UTC by zeroalphat

Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>

2022-10-14 10:10 UTC, morimoto-cybozu requested changes

2022-10-17 01:09 UTC, morimoto-cybozu approved these changes
LGTM

2022-10-17 01:15 UTC, zeroalphat commented on ignition-template/main.go
> +	fmt.Println(string(data))
Thank you for your detailed explanation.
I now understand why I shouldn't just use the print function to output data.

2022-10-17 02:41 UTC, morimoto-cybozu approved these changes

2022-10-17 04:25 UTC, merged