Update Ubuntu from 20.04 to 22.04
cybozu-go/neco pull request #2131
Opened 2022-10-26 01:46 UTC by zeroalphat

2022-11-01 06:08 UTC, morimoto-cybozu requested changes

2022-11-01 06:08 UTC, morimoto-cybozu commented on installer/autoinstall/user-data
> +    cat <<EOF | sudo tee /target/etc/systemd/networkd.conf.d/01-cybozu.conf
```suggestion
    sudo tee /target/etc/systemd/networkd.conf.d/01-cybozu.conf << EOF
```

If you don't need output to stdout, use `> /dev/null`.

2022-11-01 07:01 UTC, zeroalphat commented on installer/Makefile
> +BIRD2_URL = http://archive.ubuntu.com/ubuntu/pool/universe/b/bird2/bird2_2.0.10-2_amd64.deb
I didn't look into the package information used by jammy very much.
Since there was no need to use a newer version, I changed it to the same version used by jammy.

2022-11-01 07:03 UTC, zeroalphat commented on installer/autoinstall/user-data
> +    cat <<EOF | sudo tee /target/etc/systemd/networkd.conf.d/01-cybozu.conf
There was no need to output to stdout, so I changed it to put it out to `/dev/null`

2022-11-01 07:07 UTC, zoetrope commented on installer/Makefile
> +		-append_partition 2 28732ac11ff8d211ba4b00a0c93ec93b --interval:local_fs:2871452d-2879947d::'$(ORIGINAL_ISO_PATH)' \
Where did this ID come from?
Please describe in the comments.

2022-11-01 07:11 UTC, zoetrope commented on installer/patch/grub.cfg
> +	linux	/casper/vmlinuz fsck.mode=skip quiet autoinstall "ds=nocloud;s=/cdrom/autoinstall/" ---
Please describe why `fsck.mode=skip` is used in the comment.
A link to the issue will be helpful.

2022-11-02 02:00 UTC, zeroalphat commented on installer/Makefile
> +		-append_partition 2 28732ac11ff8d211ba4b00a0c93ec93b --interval:local_fs:2871452d-2879947d::'$(ORIGINAL_ISO_PATH)' \
I have added the referenced article to my comment.
dcef77cf69da3b3942899f05995e55902ac55e74

2022-11-02 02:04 UTC, zeroalphat commented on installer/patch/grub.cfg
> +	linux	/casper/vmlinuz fsck.mode=skip quiet autoinstall "ds=nocloud;s=/cdrom/autoinstall/" ---
I added a comment regarding fsck.mode.
I added comments in other areas where the changes were not readily apparent.

2022-11-07 04:19 UTC, zoetrope approved these changes

2022-11-08 04:51 UTC, zeroalphat commented
The ISO image was not the version with the libssl3 security fix, so it was changed to be installed manually.
58067849ee2bb3cd95779b4e2c7d85822fa8fe67

2022-11-10 06:55 UTC, zoetrope approved these changes
LGTM

2022-11-11 06:38 UTC, zeroalphat commented
I am sorry to ask you to review anything.
I changed the implementation to not use `apt-key` when adding docker repositories.

2022-11-14 02:01 UTC, zoetrope commented on README.md
> +$ curl -o /etc/apt/keyrings/docker-key.asc -fsSL https://download.docker.com/linux/ubuntu/gpg
Is `sudo` not required?

2022-11-14 04:48 UTC, zeroalphat commented on README.md
> +$ curl -o /etc/apt/keyrings/docker-key.asc -fsSL https://download.docker.com/linux/ubuntu/gpg
Sorry, I forgot to add `sudo`.
I upgraded the placemat version as well.
296c984489d4a2d5b96d421b978d9eaf6ecfd0ce

2022-11-14 07:23 UTC, zoetrope approved these changes

2022-11-17 06:18 UTC, morimoto-cybozu requested changes

2022-11-17 06:18 UTC, morimoto-cybozu commented on installer/setup/docker.go
> +	if os.WriteFile(neco.DockerKeyringFile, data, 0644); err != nil {
```suggestion
	if err := os.WriteFile(neco.DockerKeyringFile, data, 0644); err != nil {
```

2022-11-17 06:18 UTC, morimoto-cybozu commented on installer/setup/docker.go
> +	if os.WriteFile(neco.DockerSourceListFile, []byte(repo), 0644); err != nil {
```suggestion
	if err := os.WriteFile(neco.DockerSourceListFile, []byte(repo), 0644); err != nil {
```

2022-11-17 06:18 UTC, morimoto-cybozu commented on installer/setup/docker.go
> +		return fmt.Errorf("failed to create%s: %w", neco.DockerKeyringFile, err)
```suggestion
		return fmt.Errorf("failed to create %s: %w", neco.DockerKeyringFile, err)
```

2022-11-17 06:18 UTC, morimoto-cybozu commented on installer/setup/docker.go
> +		return fmt.Errorf("failed to create%s: %w", neco.DockerSourceListFile, err)
```suggestion
		return fmt.Errorf("failed to create %s: %w", neco.DockerSourceListFile, err)
```

2022-11-17 06:45 UTC, zeroalphat commented on installer/setup/docker.go
> +	if os.WriteFile(neco.DockerKeyringFile, data, 0644); err != nil {
Fix assignment omissions to variables at 8b046730ca62128ee93007d1205897a828597bca.

2022-11-17 06:50 UTC, morimoto-cybozu approved these changes
LGTM

2022-12-16 04:38 UTC, zoetrope approved these changes

2023-01-24 01:44 UTC, merged