add stage1 cluster settings
cybozu-go/neco pull request #2174
Opened 2022-12-09 09:57 UTC by umezawatakeshi

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

2022-12-15 07:15 UTC, kmdkuk submitted a review, later dismissed
LGTM

2022-12-15 08:11 UTC, masa213f requested changes

2022-12-22 00:42 UTC, masa213f requested changes

2022-12-22 00:42 UTC, masa213f commented on worker/operator.go
> +	if env == neco.TestEnv {
Like this?
```suggestion
	if env == neco.DevEnv {
```

2022-12-22 15:37 UTC, masa213f approved these changes
LGTM

2022-12-23 02:44 UTC, umezawatakeshi commented
rebased (due to artifacts.go)

2022-12-23 07:14 UTC, masa213f approved these changes
LGTM

2022-12-28 06:51 UTC, kmdkuk approved these changes
LGTM

2023-01-10 02:53 UTC, merged