wip
cybozu-go/neco pull request #2367
Opened 2023-09-19 06:13 UTC by YZ775

Signed-off-by: YZ775 <yuzuki-mimura@cybozu.co.jp>

2023-11-13 07:13 UTC, masa213f requested changes

2023-11-13 07:13 UTC, masa213f commented on pkg/sabakan-state-setter/controller.go
> +	sabakanTLSClient, err := newSabakanGQLClient(sabakanAddressHTTPS)
Please fix `newSabakanGQLClient` and `SabakanClientWrapper` as follows.
The caller should have only one SabakanClientWrapper.

```suggestion
	sabakanClient, err := newSabakanClient(sabakanAddress, sabakanAddressHTTPS)
```

2023-11-14 07:19 UTC, YZ775 commented on pkg/sabakan-state-setter/controller.go
> +	sabakanTLSClient, err := newSabakanGQLClient(sabakanAddressHTTPS)
I changed `SabakanClientWrapper` to have two sabakan client(HTTP and HTTPS) instead of the Controller having two sabakan client.

2023-11-17 08:03 UTC, masa213f requested changes

2023-11-17 08:03 UTC, masa213f commented on pkg/sabakan-state-setter/sabakan.go
> +		sabakanClient:    sabakanClient,
Is `sabacWrapper.sabakanClient` being used?

2023-11-17 08:03 UTC, masa213f commented on progs/sabakan/conf.go
> +
OK. Please remove it.

2023-11-17 09:13 UTC, YZ775 commented on pkg/sabakan-state-setter/sabakan.go
> +		sabakanClient:    sabakanClient,
I noticed that `sabakanClient` is not used bacause all API calls in sabakan-state-setter except for `/crypts` are using GraphQL.
I'll remove this.

2023-11-21 05:59 UTC, masa213f submitted a review, later dismissed
LGTM!

2023-11-22 02:58 UTC, YZ775 commented
wait merge until operation of step1 completed.

2023-11-29 01:52 UTC, masa213f approved these changes

2023-11-29 02:33 UTC, merged