[wip] Sabakan TLS step1
cybozu-go/neco pull request #2394
Opened 2023-10-13 05:21 UTC by YZ775

2023-10-16 07:43 UTC, masa213f requested changes

2023-10-16 07:43 UTC, masa213f commented on constants.go
> +	SabakanTLSKeyFile  = filepath.Join(SabakanDir, "sabakan-tls.key")
Please make it clear that they are server certificates.

```suggestion
	SabakanServerCertFile = filepath.Join(SabakanDir, "sabakan-server.crt")
	SabakanServerKeyFile  = filepath.Join(SabakanDir, "sabakan-server.key")
```

2023-10-16 07:43 UTC, masa213f commented on pkg/neco/cmd/init_local.go
> +				return neco.StartService(ctx, neco.SabakanService)
Do we need to restart the sabakan service at this time?
When we will run `neco-init sabakan`, the new sabakan will not be released yet, won't it?

2023-10-16 07:43 UTC, masa213f commented on pkg/neco/cmd/init_local.go
> +	}
Why did you add this check?

2023-10-16 07:43 UTC, masa213f commented on pkg/neco/cmd/init_local.go
> +func issueSabakanTLSCerts(ctx context.Context, vc *api.Client, cert, key string) error {
Please make it clear that this is for server certificates.

```suggestion
func issueSabakanServerCerts(ctx context.Context, vc *api.Client, cert, key string) error {
```

2023-10-16 07:43 UTC, masa213f commented on pkg/neco/cmd/init_data.go
> +		_, err = sabakanClient.AssetsUpload(ctx, "sabakan-tls-ca.crt", neco.ServerCAFile, nil)
Please create a function in `progs/sabakan` for this logic.

2023-10-18 07:35 UTC, YZ775 commented on pkg/neco/cmd/init_local.go
> +				return neco.StartService(ctx, neco.SabakanService)
I wrote this code before I came up with the idea of splitting deploy operations to 2 step, so I expected that update of  sabakan and neco command would be same time.
I'll remove this restart logic.

2023-10-18 07:39 UTC, YZ775 commented on pkg/neco/cmd/init_local.go
> +	}
I want to make `neco-init sabakan` command to be idempotent. so I need to send the existence of the cert file.
This check returns `ErrExist` when the cert file are already exists in specified directry.

2023-11-01 06:29 UTC, masa213f requested changes

2023-11-01 06:29 UTC, masa213f commented on pkg/neco/cmd/init_local.go
> +	}
Are there any side effects of issuing a new cert?

I assume that the `neco init-local` is executed only once during initializing the boot server. So, it is not necessary to be idempotent.

If the side effects of issuing a new cert are negligible, we can overwrite it.

2023-11-01 06:29 UTC, masa213f commented on pkg/neco/cmd/init_local.go
> +				var isActive bool
Do you avoid the error by turning off the sabakan service before the operation?
I don't want to leave code that executes only once for updating the sabakan.

2023-11-06 04:59 UTC, masa213f requested changes

2023-11-06 04:59 UTC, masa213f commented on pkg/neco/cmd/init_local.go
> +					fmt.Printf("etcdpasswd certificate already exists in %s.  skipping issue cert\n", neco.SabakanEtcdCertFile)
```suggestion
					fmt.Printf("etcdpasswd certificate already exists in %s.  skipping issue cert\n", neco.EtcdpasswdCertFile)
```

2023-11-06 04:59 UTC, masa213f commented on pkg/neco/cmd/init_local.go
> +					fmt.Printf("cke certificate already exists in %s.  skipping issue cert\n", neco.SabakanEtcdCertFile)
```suggestion
					fmt.Printf("cke certificate already exists in %s.  skipping issue cert\n", neco.CKECertFile)
```

2023-11-06 04:59 UTC, masa213f commented on pkg/neco/cmd/init_local.go
> +					fmt.Printf("sabakan certificate already exists in %s.  skipping issue cert\n", neco.SabakanEtcdCertFile)
Why don't you use `log.Info()`?

2023-11-07 09:25 UTC, masa213f approved these changes
LGTM

2023-11-08 00:59 UTC, masa213f approved these changes

2023-11-08 04:18 UTC, merged