Upgrade dep by regular upgrade
cybozu-go/neco pull request #2541
Opened 2024-04-11 05:00 UTC by takara9

This PR is the part of the regular update work.

2024-04-15 13:22 UTC, morimoto-cybozu requested changes
Please clean up your commits before requesting review.

I'm concerned about unmaintained components, e.g., node-exporter.

2024-04-16 08:05 UTC, takara9 commented
@morimoto-cybozu 
Thank you as always. I really appreciate it.
I did cleanup commit messages and update dependency modules which include node-exporter etc.

2024-04-16 08:49 UTC, morimoto-cybozu requested changes

2024-04-16 08:49 UTC, morimoto-cybozu commented on Makefile.common
> +KUSTOMIZE_VERSION = 5.4.1
Argo CD v2.10.2 uses Kustomize v5.2.1.
Argo CD v2.10.7 also uses Kustomize v5.2.1.

```suggestion
KUSTOMIZE_VERSION = 5.2.1
```

2024-04-16 08:49 UTC, morimoto-cybozu commented on Makefile.tools
> -	$(CP) $(KUSTOMIZE_DLDIR)/windows_amd64/kustomize $(WINDOWS_BINDIR)/kustomize.exe
Why?

2024-04-16 08:55 UTC, takara9 commented on Makefile.tools
> -	$(CP) $(KUSTOMIZE_DLDIR)/windows_amd64/kustomize $(WINDOWS_BINDIR)/kustomize.exe
Exe file name is changed in kustomize 5.4.1.

2024-04-16 09:29 UTC, closed without merging