[WIP] add neco-rebooter
cybozu-go/neco pull request #2573
Opened 2024-06-05 07:34 UTC by YZ775

2024-06-26 02:01 UTC, umezawatakeshi requested changes

2024-06-27 04:48 UTC, YZ775 commented on pkg/neco-rebooter/controller.go
> +		}
The Status of reboot queue is only taken in first section of runOnce. So putting `moveNextGroup at the bottom of runOnce  will cause following problems.

- Even if reboot queue entry is dequeued and become empty  in the steps before moveNextGroup, we can not detect emptiness of reboot queue in moveNextGroup at same loop of runOnce.
- If reboot queue is empty at first and entry is added in addRebootListEntry, the controller regards reboot queue is empty and moveNextGroup is executed even if reboot-queue is not empty actually.

2024-06-27 04:53 UTC, YZ775 commented on pkg/neco-rebooter/controller.go
> +		}
If we check the status of reboot queue by using `c.necoStorage.GetRebootListEntries(ctx)` before `moveNextGroup()`, these problems are solved, but I impletemted so because I thought that reducing GET requests to etcd is more important than naturality of steps.

2024-06-27 09:06 UTC, umezawatakeshi commented on pkg/neco-rebooter/config.go
> +type MatchLabels map[string]string
I don't think MatchLabels should have its (alias) type as Kubernetes' MatchLabels doesn't. However, I leave this point to your decision.

2024-06-27 09:11 UTC, umezawatakeshi requested changes

2024-06-27 09:11 UTC, umezawatakeshi commented on pkg/neco/cmd/rebooter.go
> +		defer configFile.Close()
still wrong.
```suggestion
		defer ckeConfigFile.Close()
```

2024-06-28 00:11 UTC, YZ775 commented on pkg/neco/cmd/rebooter.go
> +		defer configFile.Close()
Thank you. I only changed name of variable and forgotten to change defer(). I fixed it.

2024-06-28 08:17 UTC, umezawatakeshi commented
I satisified the fix.
After the artifacts are updated (https://github.com/cybozu-go/neco/pull/2594), please rebase AND squash the commits.

2024-07-01 02:09 UTC, YZ775 commented on storage/neco-rebooter.go
> +	resp, err := s.etcd.Get(ctx, KeyNecoRebooterLeader, opts...)
@morimoto-cybozu 
> concurrency.NewElection() and e.Leader() might be better.

I understand and agree this.

>We already depend on the implementation to write dctest

Could you give me  the location of code that depend on the implementation? I could't find it.

2024-07-01 10:26 UTC, morimoto-cybozu commented on storage/neco-rebooter.go
> +	resp, err := s.etcd.Get(ctx, KeyNecoRebooterLeader, opts...)
@YZ775 
`getLeaderNode()` and its copy `getNecoRebooterLeaderNode()` use `--prefix` option.
https://github.com/cybozu-go/neco/blob/release-2024.06.25-29602/dctest/sabakan_state_setter_test.go#L123

They compare `CreateRevision` to find the oldest key-value pair.
https://github.com/cybozu-go/neco/blob/release-2024.06.25-29602/dctest/sabakan_state_setter_test.go#L155

2024-07-02 01:10 UTC, YZ775 commented on storage/neco-rebooter.go
> +	resp, err := s.etcd.Get(ctx, KeyNecoRebooterLeader, opts...)
@morimoto-cybozu 
Thank you. I understand.
I think sabakan-state-setter uses such way  in `getLeaderNode` because it's difficult to obtain etcdClient in dctest.
But, there are `neco rebooter leader` command for neco-rebooter. So I changed the code to use this commnad instead of `getNecoRebooterLeaderNode()`.

2024-07-03 13:31 UTC, morimoto-cybozu requested changes
I'm still reading the controller code.

2024-07-03 13:39 UTC, morimoto-cybozu commented on pkg/neco/cmd/rebooter_reboot_woker.go
> +		}
These checks should be done in `for _, machine := range machines` loop, especially because `machine.Spec.IPv4[0]` can cause a panic.

2024-07-04 04:24 UTC, YZ775 commented
Thank you for reviewing. I fixed the the code you commented, at this point.

2024-07-08 06:07 UTC, morimoto-cybozu requested changes

2024-07-09 01:12 UTC, YZ775 commented on pkg/neco-rebooter/controller.go
> +func watchLeaderKey(ctx context.Context, session *concurrency.Session, leaderKey string) error {
I'm not familiar with it too.
I implemented the code same as sabakan-state-setter.
https://github.com/cybozu-go/neco/blob/f3d25774a7f615ad679f195cb28cfc4533946bea/pkg/sabakan-state-setter/controller.go#L197


And I found example is described here.
https://github.com/zoetrope/etcd-book/blob/master/docs/chapter3.md#%E3%83%AA%E3%83%BC%E3%83%80%E3%83%BC%E3%81%AE%E7%9B%A3%E8%A6%96

2024-07-09 01:23 UTC, YZ775 commented on pkg/neco-rebooter/controller.go
> +				ctx.Err()
I referenced here.
https://github.com/cybozu-go/neco/blob/f3d25774a7f615ad679f195cb28cfc4533946bea/pkg/sabakan-state-setter/controller.go#L173

I thought if ctx is cancelled from caller, I want to stop the goroutine. Doesn't it necessary?

2024-07-09 01:37 UTC, YZ775 commented on pkg/neco-rebooter/controller.go
> +		}
I prefer the former style because we can conduct a test for the condition by function-level.
And I thought readability is no problem because there are only three functions executed in same loop. (Of course if there are many functions, it would be matter)

Would it better to change to the later style?

2024-07-09 05:35 UTC, YZ775 commented on pkg/neco-rebooter/controller.go
> +		}
I found better way to test condition in latter style.
I'm currently fixing the code and tests.

2024-07-09 11:19 UTC, morimoto-cybozu commented on pkg/neco-rebooter/controller.go
> +				ctx.Err()
I agree that it is necessary to stop in the case of `ctx.Done()`.
`return` of Line 362 is meaningful.

`ctx.Err()` just returns `err` and it does not have a visible side-effect.
You can (1) return without calling `ctx.Err()` or (2) log the value of `ctx.Err()` and return.

2024-07-10 01:13 UTC, YZ775 commented on pkg/neco-rebooter/controller.go
> +				ctx.Err()
Thank you. I understand. I called `ctx.Err()`mistakenly even if this function does not have error as return value.

I will adopt the way of (1).

2024-07-10 01:59 UTC, morimoto-cybozu requested changes

2024-07-10 09:11 UTC, morimoto-cybozu approved these changes

2024-07-11 00:15 UTC, YZ775 commented
I squashed fixup commits.

2024-07-11 04:44 UTC, YZ775 commented
@umezawatakeshi
I completed fixup for review comment by @morimoto-cybozu .
Could you check the PR please?

2024-07-11 05:00 UTC, umezawatakeshi approved these changes

2024-07-16 04:48 UTC, merged