update audit log policy
cybozu-go/neco pull request #2600
Opened 2024-07-10 08:16 UTC by YZ775

2024-07-10 23:48 UTC, zeroalphat approved these changes
LGTM

2024-07-16 02:00 UTC, masa213f requested changes

2024-07-16 05:13 UTC, masa213f approved these changes
LGTM!

2024-07-16 05:22 UTC, YZ775 commented
@masa213f Thank you for review!

2024-07-16 05:22 UTC, merged