Add systemd service and timer for triggering daily reboot all nodes o…
cybozu-go/neco pull request #2637
Opened 2024-08-08 06:06 UTC by zeroalphat

…n dev environment

2024-08-26 04:41 UTC, masa213f requested changes
LGTM

2024-08-26 04:41 UTC, masa213f commented on debian/usr/bin/trigger-reboot-all-nodes
> +ENVIROMENT=$(${NECO_COMMAND} config get env)
Could you do early return?

```bash
ENVIROMENT=$(${NECO_COMMAND} config get env)
if [ "$ENVIROMENT" != "dev" ]; then
    echo "This script is only for dev environment"
    exit 0
fi

REBOOT_LIST=$(${NECO_COMMAND} rebooter list)
REBOOT_QUEUE=$(${CKECLI_COMMAND} rq list)
# Confirm that the reboot list and reboot queue are empty
if [ "$REBOOT_LIST" != "null" ] || [ "$REBOOT_QUEUE" != "null" ]; then 
    echo "The reboot list or reboot queueu is not empty. Skipping reboot all nodes"
    exit 0
fi

$NECO_COMMAND rebooter disable
sh -c $YES_COMMAND | $NECO_COMMAND rebooter reboot-worker --without-state retiring,retired
$NECO_COMMAND rebooter enable
```

2024-08-26 04:41 UTC, masa213f commented on debian/usr/bin/trigger-reboot-all-nodes
> +        $NECO_COMMAND rebooter enable
Could you run these command on only one boot server?
I think we can use `neco rebooter leader` or `ckecli leader`.

2024-08-26 05:14 UTC, zeroalphat commented on debian/usr/bin/trigger-reboot-all-nodes
> +        $NECO_COMMAND rebooter enable
I failed to take into consideration that it works on all boot servers.
I added a process to check if the server the script is running on is a leader.

2024-08-28 01:55 UTC, masa213f requested changes

2024-08-28 01:55 UTC, masa213f commented on debian/usr/bin/trigger-reboot-all-nodes
> +if [ "$REBOOT_LIST" != "null" ] && [ "$REBOOT_QUEUE" != "null" ]; then
Is it correct? Should we change to `||`?

2024-08-28 02:01 UTC, zeroalphat commented on debian/usr/bin/trigger-reboot-all-nodes
> +if [ "$REBOOT_LIST" != "null" ] && [ "$REBOOT_QUEUE" != "null" ]; then
Thank you for pointing this out.
I had overlooked the need to change the conditional judgement 🙇

2024-08-28 07:03 UTC, masa213f approved these changes
LGTM

2024-09-09 00:43 UTC, merged