fix reboot_test and collectEntries
cybozu-go/neco pull request #2663
Opened 2024-09-06 03:29 UTC by YZ775

2024-09-10 05:08 UTC, masa213f requested changes

2024-09-10 05:08 UTC, masa213f commented on dctest/reboot_test.go
> +			racksTmp = append(racksTmp, rack[len(rack)-1:])
Why are you cut out numbers here?
In most reference points, `fmt.Sprintf("rack%s", racks[0])` is used. And it making the code difficult to read.

2024-09-10 05:18 UTC, YZ775 commented on dctest/reboot_test.go
> +			racksTmp = append(racksTmp, rack[len(rack)-1:])
I decided to extract only rack numbers because the format of "rack" is different between application.

- k8s label: `topology.kubernetes.io/zone=rack1`
- sabakan option: `sabactl machines get --rack=1`

2024-09-10 09:32 UTC, masa213f commented on dctest/reboot_test.go
> +			racksTmp = append(racksTmp, rack[len(rack)-1:])
I know. How about extracting the number only in neco-rebooter args?
Also, does `sh -c` work as expected?

```golang
rebootCmd := fmt.Sprintf("yes | neco rebooter reboot-worker --rack=%s", racks[0][4:] /* extract a rack number: "rackN" -> "N" */)
execSafeAt(bootServers[0], "sh", "-c", "'"+rebootCmd+"'")
```
or
```golang
execSafeAt(bootServers[0], "yes", "|", "neco", "rebooter", "reboot-worker", "--rack="+racks[0][4:] /* extract a rack number: "rackN" -> "N" */)
```

2024-09-10 09:34 UTC, masa213f commented on dctest/reboot_test.go
> +		}
How about to use `Expect()` here too?

2024-09-11 00:10 UTC, YZ775 commented on dctest/reboot_test.go
> +			racksTmp = append(racksTmp, rack[len(rack)-1:])
I understand. and I fixed the code to extract number only in neco-rebooter command.

And, `sh-c` works fine.
It had been used before neco-rebooter was implemented like below.
https://github.com/cybozu-go/neco/blob/98bf903b8d9e278fd4c81767b4ed48895783810b/dctest/reboot_test.go#L83

2024-09-11 01:40 UTC, masa213f requested changes

2024-09-11 01:40 UTC, masa213f commented on dctest/reboot_test.go
> +		Expect(err).NotTo(HaveOccurred())
Nice. But why don't you keep the `stdout` and `stderr`?
We can pass the optionalDescription, if we want.

https://github.com/onsi/gomega/blob/7cabed651e981da0c7d0219ad7208626cef58016/gomega_dsl.go#L524

2024-09-11 01:40 UTC, masa213f commented on dctest/reboot_test.go
> +			if strings.Contains(string(stdout), racks[1]) {
How about use `strings.TrimSpace`?

2024-09-17 01:16 UTC, masa213f approved these changes
LGTM

2024-09-17 04:00 UTC, merged