implement non-graceful shutdown
cybozu-go/neco pull request #2702
Opened 2024-10-24 07:39 UTC by YZ775

2025-02-17 05:02 UTC, masa213f commented on pkg/neco/cmd/non_graceful_shutdown.go
> +type CephCluster struct {
This is fine. But, IMO, `NamespacedName` is enough.
https://pkg.go.dev/k8s.io/apimachinery/pkg/types#NamespacedName

2025-02-17 05:26 UTC, YZ775 commented on pkg/neco/cmd/non_graceful_shutdown.go
> +	outOfServiceTaintKey          = "node.kubernetes.io/out-of-service"
I didn't know the constant. I'll fix to use that.

2025-02-17 05:28 UTC, YZ775 commented on pkg/neco/cmd/non_graceful_shutdown.go
> +	}
Thank you! I wanted to implement without using file, but I haven't found the way.
I'll fix to use this way.

2025-02-17 06:46 UTC, YZ775 commented
I'm checking that the fix works fine in CI now.
https://github.com/cybozu-private/neco-apps/actions/runs/13364264101

2025-02-25 06:54 UTC, YZ775 commented
CI is passed.
@masa213f

2025-02-27 04:37 UTC, masa213f requested changes

2025-02-27 04:37 UTC, masa213f commented on pkg/neco/cmd/non_graceful_shutdown_cleanup.go
> +		}
It is not used.
```suggestion
		opt := sabakanMachinesGetOpts{}
		opt.params = map[string]*string{
			"ipv4": &node,
		}
```

2025-02-27 06:40 UTC, YZ775 commented
CI
https://github.com/cybozu-private/neco-apps/actions/runs/13560312605

2025-02-28 00:07 UTC, merged