Set systemReserved and plus
cybozu-go/neco pull request #2746
Opened 2024-12-11 23:45 UTC by takara9

2024-12-12 07:07 UTC, morimoto-cybozu requested changes

2024-12-12 07:07 UTC, morimoto-cybozu commented on etc/cke-template.yml
> +      #  memory.available: "0%"
Please delete unnecessary lines.

If you think that this configuration should become necessary in the near future but we have some reason to exclude it now, please leave a description as a comment.

2024-12-12 07:07 UTC, morimoto-cybozu commented on etc/cke-template.yml
> +      - pods
This seems the same as the default.
If you don't change `enforceNodeAllocatable`, `evictionHard`, nor `systemReserved`, this PR will change nothing.

2024-12-13 04:56 UTC, takara9 commented on etc/cke-template.yml
> +      #  memory.available: "0%"
plsease see evictionHard in the table at this URL.
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration

"0%" is to explicitly disable evition.
It need to prevent pod evict from low memory node.
if evictionHard.memory is not set,  when memory fewer than low, Pod moved other node.


It would be fine to remove the settings and re-set them based on the results of the experiment.

2024-12-13 04:57 UTC, takara9 commented on etc/cke-template.yml
> +      - pods
I think it should be explicitly set, as there were many comments in the meeting that people did not understand the default values.

2024-12-20 06:45 UTC, closed without merging